"""Markdown to PDF document factory.

This module turns Markdown source text into polished, print-ready PDF
documents with a minimalist editorial design:

1. the (optional) YAML-ish front matter is extracted for metadata,
2. the body is converted to HTML by ``markdown-it-py`` (CommonMark +
   GFM tables, strikethrough and task lists) with Pygments syntax
   highlighting for fenced code blocks,
3. the result is wrapped in a dedicated template and stylesheet,
   bundled with the library, and
4. rendered by the regular :class:`weasyprint.HTML` machinery.

The entry points are:

- the :class:`Markdown` class, mirroring the :class:`weasyprint.HTML`
  API,
- the ``weasyprint file.md file.pdf`` command, which auto-detects
  Markdown inputs.

"""

import re
from pathlib import Path

from markdown_it import MarkdownIt
from mdit_py_plugins.gfm import gfm_plugin
from pygments import highlight as _pygments_highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name
from pygments.util import ClassNotFound

from . import VERSION
from .logger import LOGGER

__all__ = ['MARKDOWN_EXTENSIONS', 'Markdown']

#: File extensions that trigger the Markdown pipeline automatically.
MARKDOWN_EXTENSIONS = ('.md', '.markdown', '.mdown', '.mkd')

_RESOURCES_DIR = Path(__file__).parent / 'resources' / 'markdown'
_TEMPLATE = (_RESOURCES_DIR / 'template.html').read_text(encoding='utf-8')
_STYLESHEET = (_RESOURCES_DIR / 'markdown.css').read_text(encoding='utf-8')

_URL_RE = re.compile(r'^[a-zA-Z][a-zA-Z0-9+.-]*:')
_FRONT_MATTER_DELIMITERS = ('---', '+++', '...')

_TASK_INPUT_RE = re.compile(
    r'<input class="task-list-item-checkbox"([^>]*)>')

_DATE_RE = re.compile(r'^\d{4}-\d{2}-\d{2}$')

# GFM tables generated by markdown-it, whose alignment styles only
# land on header cells.
_TABLE_RE = re.compile(
    r'<table>\s*<thead>\s*<tr>\s*((?:<th[^>]*>.*?</th>\s*)+)</tr>\s*</thead>'
    r'\s*<tbody>(.*?)</tbody>\s*</table>', re.S)
_ROW_RE = re.compile(r'<tr>.*?</tr>', re.S)
_TH_RE = re.compile(r'<th( style="[^"]*")?>')
_TD_RE = re.compile(r'<td( style="[^"]*")?>')


def _is_url(source):
    return bool(_URL_RE.match(source))


def parse_front_matter(text):
    """Split an optional front matter block from Markdown source.

    Only flat ``key: value`` lines are supported, enough for document
    metadata without pulling in a YAML dependency.  A full YAML document
    is deliberately not supported: complex values are simply ignored.

    :return: a ``(body, metadata)`` tuple.

    """
    lines = text.splitlines()
    if not lines or lines[0].strip() not in _FRONT_MATTER_DELIMITERS:
        return text, {}
    end = None
    for index in range(1, len(lines)):
        if lines[index].strip() in _FRONT_MATTER_DELIMITERS:
            end = index
            break
    if end is None:
        # Not a valid front matter block, keep the text as-is.
        return text, {}

    metadata = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        key, separator, value = line.partition(':')
        if not separator or not key.strip():
            # Tolerate richer YAML (lists, nesting…) by ignoring what we
            # do not understand: front matter here is metadata, not data.
            continue
        key = key.strip().lower()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '"\'':
            value = value[1:-1]
        if key:
            metadata[key] = value
    return '\n'.join(lines[end + 1:]), metadata


def _highlight(code, language, attrs=None):
    """Highlight ``code`` with Pygments, returning HTML spans.

    Return :obj:`None` when the language is unknown or missing, letting
    markdown-it render the block as plain escaped text.

    """
    if not language:
        return None
    try:
        lexer = get_lexer_by_name(language, stripnl=False, ensurenl=False)
    except ClassNotFound:
        return None
    formatter = HtmlFormatter(nowrap=True)
    return _pygments_highlight(code, lexer, formatter).rstrip('\n')


def _make_markdown_parser():
    markdown = MarkdownIt('commonmark', {'highlight': _highlight})
    # GFM: tables, strikethrough, task lists.
    markdown.use(gfm_plugin)
    # Typographic niceties: curly quotes, fractions, …
    markdown.enable(['smartquotes', 'replacements'])
    return markdown


def _task_list_checkboxes(html):
    """Replace form checkboxes with printable, styleable markers."""
    def replace(match):
        checked = 'checked' in match.group(1)
        classes = 'checkbox checked' if checked else 'checkbox'
        return f'<span class="{classes}"></span>'
    return _TASK_INPUT_RE.sub(replace, html)


def _align_table_columns(html):
    """Copy header cell alignment onto the matching body cells.

    markdown-it only sets ``text-align`` on ``<th>`` cells: propagate
    it to the ``<td>`` cells below, so aligned columns read as such.

    """
    def fix_table(match):
        header_cells, tbody = match.group(1), match.group(2)
        styles = [m.group(1) or '' for m in _TH_RE.finditer(header_cells)]
        if not any(styles):
            return match.group(0)

        def fix_row(row_match):
            row = row_match.group(0)
            cells = _TD_RE.findall(row)
            if len(cells) != len(styles):
                # Nested or hand-written table: leave it alone.
                return row
            index = -1

            def replace_cell(cell_match):
                nonlocal index
                index += 1
                style = styles[index]
                return f'<td{style}>' if style else '<td>'

            return _TD_RE.sub(replace_cell, row)

        tbody = _ROW_RE.sub(fix_row, tbody)
        return (
            f'<table>\n<thead>\n<tr>\n{header_cells}</tr>\n</thead>\n'
            f'<tbody>{tbody}</tbody>\n</table>')

    return _TABLE_RE.sub(fix_table, html)


def render_markdown(text, fallback_title=None):
    """Render Markdown source to the body HTML of the template.

    When the document starts with a level-1 heading, that heading is
    used as the document title and removed from the body, so that it is
    not duplicated under the cover page.

    :return: a ``(body_html, title)`` tuple.

    """
    markdown = _make_markdown_parser()
    tokens = markdown.parse(text)
    title = None
    if tokens and tokens[0].type == 'heading_open' and tokens[0].tag == 'h1':
        title = tokens[1].content
        # Drop the heading_open/inline/heading_close tokens.
        tokens = tokens[3:]
    if not title:
        title = fallback_title or 'Untitled document'
    body = markdown.renderer.render(tokens, markdown.options, {})
    body = _task_list_checkboxes(body)
    return _align_table_columns(body), title


#: Documents whose body is shorter than this keep their title block on
#: the first page (letterhead style) instead of a dedicated cover page.
COMPACT_THRESHOLD = 1200


def build_html(body, title, metadata=None, lang=None):
    """Wrap rendered Markdown in the print HTML template.

    :param str body: rendered Markdown, as HTML.
    :param str title: document title, used on the cover and in metadata.
    :param dict metadata: document metadata (from the front matter).
    :param str lang: document language as a BCP-47 tag, ``'en'`` by
        default, or the ``lang`` metadata entry.

    The ``cover`` metadata entry selects the first-page layout:
    ``'auto'`` (default) uses a full cover page unless the document is
    short, ``'full'`` and ``'compact'`` force a layout.

    :return: the HTML document, as a string.

    """
    from html import escape as escape_html

    metadata = metadata or {}
    lang = lang or metadata.get('lang') or 'en'
    subtitle = metadata.get('subtitle')
    author = metadata.get('author')
    date = metadata.get('date')
    kicker = metadata.get('kicker') or metadata.get('label')
    description = metadata.get('description')

    cover_mode = metadata.get('cover') or 'auto'
    if cover_mode not in ('auto', 'full', 'compact'):
        LOGGER.warning(
            'Unknown cover mode: %r, falling back to auto.', cover_mode)
        cover_mode = 'auto'
    if cover_mode == 'auto':
        cover_mode = 'compact' if len(body) <= COMPACT_THRESHOLD else 'full'

    cover = []
    if kicker:
        cover.append(f'<p class="cover-kicker">{escape_html(kicker)}</p>')
    cover.append(f'<h1 class="cover-title">{escape_html(title)}</h1>')
    if subtitle:
        cover.append(f'<p class="cover-subtitle">{escape_html(subtitle)}</p>')
    cover.append('<div class="cover-rule"></div>')
    if author or date:
        meta = []
        if author:
            meta.append(
                f'<span class="cover-author">{escape_html(author)}</span>')
        if author and date:
            meta.append('<span class="cover-sep">·</span>')
        if date:
            meta.append(escape_html(date))
        cover.append(f'<p class="cover-meta">{"".join(meta)}</p>')
    cover_class = 'cover' if cover_mode == 'full' else 'cover compact'
    cover_html = '\n'.join(
        [f'<div class="{cover_class}">', *cover, '</div>'])

    font_dir = (_RESOURCES_DIR / 'fonts').as_uri()
    stylesheet = _STYLESHEET.replace('__FONT_DIR__', font_dir)

    meta_author = (
        f'<meta name="author" content="{escape_html(author)}">' if author
        else '')
    meta_description = (
        f'<meta name="description" content="{escape_html(description)}">'
        if description else '')
    # Only set the PDF creation date when it is a real ISO date, to keep
    # the output deterministic.
    meta_created = (
        f'<meta name="dcterms.created" content="{escape_html(date)}">'
        if date and _DATE_RE.match(date) else '')

    document = _TEMPLATE
    for token, value in (
            ('__LANG__', escape_html(lang, quote=True)),
            ('__VERSION__', VERSION),
            ('__DOC_TITLE__', escape_html(title)),
            ('__META_AUTHOR__', meta_author),
            ('__META_DESCRIPTION__', meta_description),
            ('__META_CREATED__', meta_created),
            ('__CSS__', stylesheet),
            ('__COVER__', cover_html),
            ('__BODY__', body)):
        document = document.replace(token, value)
    return document


class Markdown:
    """A Markdown document ready to be rendered as a PDF.

    Instances can be created with a filename, a URL, a file object or a
    string, exactly like :class:`weasyprint.HTML`::

        Markdown('report.md').write_pdf('report.pdf')

    Relative URLs in the Markdown source (typically images) are
    resolved against the document location.

    An optional flat ``key: value`` front matter provides the cover
    metadata: ``title``, ``subtitle``, ``author``, ``date``,
    ``description``, ``kicker`` (a short label above the title) and
    ``lang``.  When there is no ``title`` entry, the first level-1
    heading — or the filename — is used instead.

    """
    def __init__(self, guess=None, filename=None, url=None, file_obj=None,
                 string=None, encoding=None, base_url=None, url_fetcher=None,
                 title=None):
        if base_url is None:
            if filename is not None:
                base_url = str(Path(filename).resolve())
            elif url is not None:
                base_url = url
            elif guess is not None and isinstance(guess, str) and \
                    not _is_url(guess):
                base_url = str(Path(guess).resolve())

        if guess is not None:
            if hasattr(guess, 'read'):
                file_obj = guess
            elif isinstance(guess, str):
                if _is_url(guess):
                    url = guess
                else:
                    # Like HTML, a string guess is a filename or URL,
                    # never literal source text: a typo in a filename
                    # must not silently render an empty document.
                    filename = guess

        text = self._read_source(filename, url, file_obj, string,
                                 encoding, url_fetcher)

        body, metadata = parse_front_matter(text)
        document_title = title or metadata.get('title')
        if not document_title and filename:
            document_title = Path(filename).stem.replace('-', ' ').title()
        if not document_title and url:
            document_title = url.rsplit('/', 1)[-1].rsplit('.', 1)[0]

        self.metadata = metadata
        self.body_html, self.title = render_markdown(body, document_title)
        self.html_string = build_html(
            self.body_html, self.title, metadata)

        # Import late: weasyprint/__init__ imports this module at the
        # very end of its own initialization.
        from . import HTML
        self.html = HTML(
            string=self.html_string, base_url=base_url,
            url_fetcher=url_fetcher)

    @staticmethod
    def _read_source(filename, url, file_obj, string, encoding, url_fetcher):
        if filename is not None:
            data = Path(filename).read_bytes()
        elif file_obj is not None:
            data = file_obj.read()
            if isinstance(data, str):
                data = data.encode('utf-8')
        elif string is not None:
            data = string.encode('utf-8') if isinstance(string, str) \
                else string
        elif url is not None:
            from .urls import default_url_fetcher
            fetcher = url_fetcher or default_url_fetcher
            result = fetcher(url)
            data = result['string']
            if isinstance(data, str):
                data = data.encode('utf-8')
            encoding = encoding or result.get('encoding')
        else:
            raise TypeError('Markdown source not specified')
        return data.decode(encoding or 'utf-8-sig')

    def render(self, font_config=None, counter_style=None, color_profiles=None,
               **options):
        """Lay out and paginate the document, like
        :meth:`weasyprint.HTML.render`.

        """
        return self.html.render(
            font_config, counter_style, color_profiles, **options)

    def write_pdf(self, target=None, zoom=1, finisher=None,
                  font_config=None, counter_style=None, color_profiles=None,
                  **options):
        """Render the document to a PDF file, like
        :meth:`weasyprint.HTML.write_pdf`.

        """
        return self.html.write_pdf(
            target, zoom, finisher, font_config, counter_style,
            color_profiles, **options)

    def __str__(self):
        return self.html_string
